# Full Test Configuration
# Used for comprehensive validation on Kaggle GPU
# Extensive testing with full hyperparameters

extends: "base.yml"

global:
  device: "gpu"  # Kaggle GPU
  quick_test: false
  verbose: true

# All sections in full test
sections:
  - section_7_3_analytical
  - section_7_4_calibration
  - section_7_5_digital_twin
  - section_7_6_rl_performance
  - section_7_7_robustness

# Full durations
durations:
  section_7_3:
    minutes: 20
  section_7_4:
    minutes: 30
  section_7_5:
    minutes: 45
  section_7_6:
    minutes: 180  # 3 hours for RL
  section_7_7:
    minutes: 30

# Full hyperparameters for section 7.6
rl_training:
  algorithm: "DQN"
  episodes: 5000
  steps_per_episode: 3600  # 1 hour per episode
  buffer_size: 50000
  batch_size: 32
  
  learning_parameters:
    learning_rate: 1e-3
    gamma: 0.99
    tau: 1.0
    train_freq: 4
    gradient_steps: 1
    target_update_interval: 1000
    exploration_fraction: 0.1
    exploration_initial_eps: 1.0
    exploration_final_eps: 0.05

# Full output
output:
  save_figures: true
  save_metrics: true
  save_artifacts: true

# Checkpoint every 500 episodes
checkpoint:
  enabled: true
  frequency_episodes: 500
  rotation_keep: 3

# Full caching with long TTL
cache:
  enabled: true
  ttl_seconds: 3600  # 1 hour cache
