# Quick Test Configuration
# Used for CI/CD and rapid iteration
# Drastically reduces runtime by limiting episodes/iterations

extends: "base.yml"

global:
  device: "cpu"
  quick_test: true
  verbose: true

# Sections to run in quick test mode
sections:
  - section_7_3_analytical
  - section_7_6_rl_performance

# Reduce all durations dramatically
durations:
  section_7_3:
    minutes: 5
  section_7_6:
    minutes: 15  # Vs 180 in full test

# Quick test specific parameters
quick_test_params:
  # Section 7.6: RL Performance
  rl_training:
    episodes: 100  # Vs 5000 in full
    steps_per_episode: 120  # Vs 3600 in full
    buffer_size: 1000  # Vs 50000 in full
    batch_size: 16

# Minimal output
output:
  save_figures: false  # Skip figures in quick test
  save_metrics: true
  save_artifacts: true

# Disable checkpointing for speed
checkpoint:
  enabled: false

# Disable caching delays
cache:
  enabled: true
  ttl_seconds: 60  # Short TTL for quick iteration
