# Section 7.6: RL Performance Validation
# Configuration for R5: Performance supérieure des agents RL
#
# This config defines all test parameters for section 7.6:
# - RL agent hyperparameters (DQN/PPO)
# - Simulation scenarios
# - Evaluation metrics
# - Duration estimates
#
# Externalized from code to enable:
# - Easy parameter tuning
# - Scenario variation
# - Kaggle vs local differentiation
# - Config-based regression detection (MD5 hashing)

name: "section_7_6_rl_performance"
description: "RL agent performance validation (R5)"
revendication: "R5"

# Simulation scenarios to test
scenarios:
  - name: "traffic_light_control"
    description: "Signalized intersection with fixed vs RL control"
    revendication: "R5.1"
    
  - name: "ramp_metering"
    description: "Highway ramp metering optimization"
    revendication: "R5.2"
    
  - name: "adaptive_speed_control"
    description: "Speed harmonization with RL agent"
    revendication: "R5.3"

# Durations (estimated, for CI/CD planning)
durations:
  quick_test:
    episodes: 100            # Training episodes (vs 5000 full)
    steps_per_episode: 120   # Simulation steps (vs 3600 full)
    estimated_seconds: 120   # CI/CD timeout planning
  
  full_test:
    episodes: 5000           # Full training
    steps_per_episode: 3600  # Full simulation length
    estimated_seconds: 7200  # 2 hours on GPU

# RL Agent Hyperparameters
# Based on stable-baselines3 DQN algorithm
hyperparameters:
  algorithm: "DQN"              # Algorithm choice
  learning_rate: 1e-3           # Initial learning rate
  buffer_size: 50000            # Replay buffer size (transitions)
  learning_starts: 1000         # Timesteps before learning
  batch_size: 32                # Batch size for training
  tau: 1.0                       # Target network update rate
  gamma: 0.99                    # Discount factor
  train_freq: 4                  # Train every N steps
  gradient_steps: 1              # Gradient steps per train call
  target_update_interval: 1000   # Target network update freq
  exploration_fraction: 0.1      # Exploration decay duration
  exploration_initial_eps: 1.0   # Initial exploration epsilon
  exploration_final_eps: 0.05    # Final exploration epsilon
  policy_kwargs:
    net_arch: [256, 256]         # Hidden layer sizes
    activation_fn: "relu"        # Activation function
    normalize_images: true       # Image normalization
  
  # Baseline (fixed-time) parameters
  baseline:
    green_duration_seconds: 60   # GREEN light duration
    red_duration_seconds: 60     # RED light duration
    control_interval_seconds: 15 # Decision interval

# Evaluation metrics
metrics:
  - name: "travel_time_improvement"
    description: "% reduction in average travel time"
    threshold: 15.0              # Minimum acceptable improvement
  
  - name: "throughput_improvement"
    description: "% increase in vehicles per hour"
    threshold: 10.0
  
  - name: "stability_improvement"
    description: "Improvement in traffic stability index"
    threshold: 5.0
  
  - name: "training_convergence"
    description: "Learning curve convergence quality"
    threshold: 0.8               # Ratio of final to best reward

# Checkpointing strategy
checkpointing:
  enabled: true
  save_frequency_steps: 10000    # Save checkpoint every N steps
  keep_latest_count: 3           # Keep 3 latest checkpoints
  archive_old_on_config_change: true  # INNOVATION: Auto-archival on config mismatch

# Caching strategy (INNOVATION: Additive cache extension)
caching:
  baseline_cache_enabled: true
  baseline_cache_path: "cache/section_7_6"
  baseline_cache_duration_minimum: 3600  # Require ≥1 hour cached
  rl_cache_enabled: true
  rl_cache_include_config_hash: true     # Config-specific caching

# UXsim Visualization (INNOVATION: ARZ-to-UXsim converter)
visualization:
  enabled: true
  snapshot_times: [0, -1]        # Time indices: start and end (-1 = last)
  create_animation: true         # Generate GIF/MP4 animation
  animation_fps: 10              # Frames per second for animation
  figure_format: "png"           # 'png' or 'pdf' for snapshots
  # Additional snapshots at key times (optional)
  key_moments:
    - time_index: 1800           # Middle of simulation (30 min)
      label: "mid_simulation"
    - time_index: 3000           # Near end (50 min)
      label: "convergence"
