# Scenario Configuration for Network Testing
scenario_name: "network_test_simple"

# Simulation parameters
N: 200  # Total cells per segment (will be adjusted for network)
xmin: 0.0
xmax: 1000.0  # Length per segment (m)
t_final: 300.0  # 5 minutes
output_dt: 10.0

# Initial conditions
initial_conditions:
  type: "uniform_equilibrium"
  rho_m: 20.0  # veh/km
  rho_c: 15.0  # veh/km
  R_val: 1

# Boundary conditions
boundary_conditions:
  left:
    type: "inflow"
    state: [0.02, 20.0, 0.015, 15.0]  # [rho_m, v_m, rho_c, v_c]
  right:
    type: "outflow"

# Road quality
road:
  quality_type: "uniform"
  quality_value: 1

# Network configuration
network:
  has_network: true

  nodes:
    - id: "intersection_1"
      position: 500.0  # Position in global coordinate system
      type: "intersection"
      segments: ["segment_1", "segment_2", "segment_3", "segment_4"]

      # Traffic lights configuration
      traffic_lights:
        cycle_time: 60.0  # 60 seconds cycle
        offset: 0.0
        phases:
          - duration: 25.0
            green_segments: ["segment_1", "segment_3"]  # North-South green
          - duration: 5.0
            green_segments: []  # All red (yellow)
            yellow_segments: ["segment_1", "segment_3"]
          - duration: 25.0
            green_segments: ["segment_2", "segment_4"]  # East-West green
          - duration: 5.0
            green_segments: []  # All red (yellow)
            yellow_segments: ["segment_2", "segment_4"]

      # Queue management
      max_queue_lengths:
        motorcycle: 50.0  # meters
        car: 50.0

      # Creeping behavior
      creeping:
        enabled: true
        speed_kmh: 5.0
        threshold: 30.0  # Start creeping when queue > 30m

  segments:
    - id: "segment_1"
      length: 500.0
      start_node: "boundary_left"
      end_node: "intersection_1"
      cells: 100  # Number of cells in this segment

    - id: "segment_2"
      length: 500.0
      start_node: "intersection_1"
      end_node: "boundary_right"
      cells: 100

    - id: "segment_3"
      length: 500.0
      start_node: "boundary_top"
      end_node: "intersection_1"
      cells: 100

    - id: "segment_4"
      length: 500.0
      start_node: "intersection_1"
      end_node: "boundary_bottom"
      cells: 100

# Override network parameters if needed
enable_traffic_lights: true
enable_creeping: true
enable_queue_management: true
max_queue_length: 100.0
red_light_factor: 0.1
